/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Register and capability definitions for the Google Tensor G4 Zumapro DPU.
 *
 * These definitions are copied from the downstream cal_9865 display register
 * headers and are intentionally inert.  Do not add MMIO users without a trace
 * comparison against downstream first-frame programming.
 */

#ifndef __REGS_ZUMAPRO_DPU_H__
#define __REGS_ZUMAPRO_DPU_H__

#include <linux/bits.h>

#define ZUMAPRO_DPU_MAX_DECON			3
#define ZUMAPRO_DPU_FETCH_DPP_COUNT		14
#define ZUMAPRO_DPU_MAX_WINDOWS			14
#define ZUMAPRO_DPU_WIN_START_TIME		32

/* Downstream DPP attribute bits. */
#define ZUMAPRO_DPP_ATTR_AFBC			BIT(0)
#define ZUMAPRO_DPP_ATTR_BLOCK			BIT(1)
#define ZUMAPRO_DPP_ATTR_FLIP			BIT(2)
#define ZUMAPRO_DPP_ATTR_ROT			BIT(3)
#define ZUMAPRO_DPP_ATTR_CSC			BIT(4)
#define ZUMAPRO_DPP_ATTR_SCALE			BIT(5)
#define ZUMAPRO_DPP_ATTR_HDR			BIT(6)
#define ZUMAPRO_DPP_ATTR_SBWC			BIT(10)
#define ZUMAPRO_DPP_ATTR_HDR10_PLUS		BIT(11)
#define ZUMAPRO_DPP_ATTR_IDMA			BIT(16)
#define ZUMAPRO_DPP_ATTR_ODMA			BIT(17)
#define ZUMAPRO_DPP_ATTR_DPP			BIT(18)
#define ZUMAPRO_DPP_ATTR_SRAMC			BIT(19)
#define ZUMAPRO_DPP_ATTR_RCD			BIT(20)
#define ZUMAPRO_DPP_ATTR_SCL_COEF		BIT(21)
#define ZUMAPRO_DPP_ATTR_HDR_COMM		BIT(22)

#define ZUMAPRO_DPP0_ATTRS			0x006d0867

/* DECON main register bank. */
#define ZUMAPRO_DECON_OFFSET(_id)		(0x1000 * (_id))
#define ZUMAPRO_DECON_SHADOW_OFFSET		0x0800

#define ZUMAPRO_DECON_GLOBAL_CON		0x0020
#define ZUMAPRO_DECON_GLOBAL_CON_SRESET		BIT(28)
#define ZUMAPRO_DECON_GLOBAL_CON_10BPC		BIT(20)
#define ZUMAPRO_DECON_GLOBAL_CON_CMD_MODE	BIT(8)
#define ZUMAPRO_DECON_GLOBAL_CON_IDLE_STATUS	BIT(5)
#define ZUMAPRO_DECON_GLOBAL_CON_RUN_STATUS	BIT(4)
#define ZUMAPRO_DECON_GLOBAL_CON_EN		BIT(1)
#define ZUMAPRO_DECON_GLOBAL_CON_EN_F		BIT(0)

/*
 * Clock gating control.  Shared block: DECON(n)'s register sits at
 * 0x5000 - 0x1000 * n from that DECON's base.
 */
#define ZUMAPRO_DECON_CLOCK_CON(_id)		(0x5000 - 0x1000 * (_id))
#define ZUMAPRO_DECON_CLOCK_CON_QACTIVE_PLL	BIT(28)
#define ZUMAPRO_DECON_CLOCK_CON_QACTIVE		BIT(24)
#define ZUMAPRO_DECON_CLOCK_CON_AUTO_CG_MASK	(0x11111 << 0)

#define ZUMAPRO_DECON_TRIG_CON			0x0030
#define ZUMAPRO_DECON_HW_TRIG_SEL(_v)		((_v) << 24)
#define ZUMAPRO_DECON_HW_TRIG_SEL_MASK		GENMASK(25, 24)
#define ZUMAPRO_DECON_HW_TRIG_SEL_DDI0		0
#define ZUMAPRO_DECON_HW_TRIG_SKIP(_v)		((_v) << 16)
#define ZUMAPRO_DECON_HW_TRIG_SKIP_MASK		GENMASK(23, 16)
#define ZUMAPRO_DECON_HW_TRIG_ACTIVE_HIGH	BIT(13)
#define ZUMAPRO_DECON_HW_TRIG_EDGE_RISING	BIT(12)
#define ZUMAPRO_DECON_SW_TRIG_EN		BIT(8)
#define ZUMAPRO_DECON_HW_TRIG_MASK		BIT(4)
#define ZUMAPRO_DECON_TRIG_TIMER_CLEAR		BIT(3)
#define ZUMAPRO_DECON_TRIG_TIMER_EN		BIT(2)
#define ZUMAPRO_DECON_SW_TRIG_DET_EN		BIT(1)
#define ZUMAPRO_DECON_HW_TRIG_EN		BIT(0)

#define ZUMAPRO_DECON_SHD_REG_UP_REQ		0x0050
#define ZUMAPRO_DECON_SHD_GLOBAL		BIT(31)
#define ZUMAPRO_DECON_SHD_DQE_CGC		BIT(26)
#define ZUMAPRO_DECON_SHD_DQE_ROI		BIT(25)
#define ZUMAPRO_DECON_SHD_DQE			BIT(24)
#define ZUMAPRO_DECON_SHD_CMP			BIT(20)
#define ZUMAPRO_DECON_SHD_WIN(_win)		BIT(_win)
#define ZUMAPRO_DECON_SHD_ALL_WINDOWS		GENMASK(13, 0)

#define ZUMAPRO_DECON_INT_EN			0x0060
#define ZUMAPRO_DECON_INT_DQE_DIMMING_END	BIT(21)
#define ZUMAPRO_DECON_INT_DQE_DIMMING_START	BIT(20)
#define ZUMAPRO_DECON_INT_FRAME_DONE		BIT(13)
#define ZUMAPRO_DECON_INT_FRAME_START		BIT(12)
#define ZUMAPRO_DECON_INT_EXTRA			BIT(4)
#define ZUMAPRO_DECON_INT_MASTER		BIT(0)

#define ZUMAPRO_DECON_INT_EN_EXTRA		0x0064
#define ZUMAPRO_DECON_INT_RESOURCE_CONFLICT	BIT(4)
#define ZUMAPRO_DECON_INT_TIMEOUT		BIT(0)

#define ZUMAPRO_DECON_INT_PEND			0x0070

#define ZUMAPRO_DECON_INT_PEND_EXTRA		0x0074

#define ZUMAPRO_DECON_DATA_PATH_CON_0		0x0200
#define ZUMAPRO_DECON_ENHANCE_PATH(_v)		((_v) << 12)
#define ZUMAPRO_DECON_ENHANCE_PATH_MASK		GENMASK(15, 12)
#define ZUMAPRO_DECON_ENHANCE_DQE_ON		ZUMAPRO_DECON_ENHANCE_PATH(2)
#define ZUMAPRO_DECON_COMP_OUTIF_PATH(_v)	((_v) << 0)
#define ZUMAPRO_DECON_COMP_OUTIF_PATH_MASK	GENMASK(7, 0)

#define ZUMAPRO_DECON_BLD_BG_IMG_SIZE_PRI	0x0220

#define ZUMAPRO_DECON_OF_SPLIT_SIZE		0x0280
#define ZUMAPRO_DECON_OF_SPLIT_IDX		0x0284
#define ZUMAPRO_DECON_OF_SIZE_0			0x0290
#define ZUMAPRO_DECON_OF_SIZE_1			0x0294
#define ZUMAPRO_DECON_OF_SIZE_2			0x0298
#define ZUMAPRO_DECON_OF_TH_TYPE		0x029c
#define ZUMAPRO_DECON_OF_TH_1H			0x5
#define ZUMAPRO_DECON_OF_PIXEL_ORDER		0x02a0
#define ZUMAPRO_DECON_OF_URGENT_EN		0x02c0
#define ZUMAPRO_DECON_OF_RD_URGENT_0		0x02c4
#define ZUMAPRO_DECON_OF_RD_URGENT_1		0x02c8
#define ZUMAPRO_DECON_OF_WR_URGENT_0		0x02cc
#define ZUMAPRO_DECON_OF_DTA_CONTROL		0x02d0
#define ZUMAPRO_DECON_OF_DTA_THRESHOLD		0x02d4
#define ZUMAPRO_DECON_SRAM_EN_OF_PRI(_id)	(0x0300 + ((_id) * 4))
#define ZUMAPRO_DECON_SRAM_EN_OF_SEC(_id)	(0x0320 + ((_id) * 4))
#define ZUMAPRO_DECON_OF_HEIGHT(_v)		((_v) << 16)
#define ZUMAPRO_DECON_OF_HEIGHT_MASK		GENMASK(29, 16)
#define ZUMAPRO_DECON_OF_WIDTH(_v)		((_v) << 0)
#define ZUMAPRO_DECON_OF_WIDTH_MASK		GENMASK(13, 0)

/* DECON window and window-control banks. */
#define ZUMAPRO_DECON_WIN_OFFSET(_id)		(0x1000 * (_id))
#define ZUMAPRO_DECON_WIN_FUNC_CON_0(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0004)
#define ZUMAPRO_DECON_WIN_ALPHA1(_v)		(((_v) & 0xff) << 24)
#define ZUMAPRO_DECON_WIN_ALPHA1_MASK		GENMASK(31, 24)
#define ZUMAPRO_DECON_WIN_ALPHA0(_v)		(((_v) & 0xff) << 16)
#define ZUMAPRO_DECON_WIN_ALPHA0_MASK		GENMASK(23, 16)
#define ZUMAPRO_DECON_WIN_FUNC(_v)		(((_v) & 0xf) << 8)
#define ZUMAPRO_DECON_WIN_FUNC_MASK		GENMASK(11, 8)
#define ZUMAPRO_DECON_WIN_FUNC_USER_DEFINED	0xd
#define ZUMAPRO_DECON_WIN_ALPHA_MULT_SRC_SEL(_v) \
		(((_v) & 0x3) << 0)
#define ZUMAPRO_DECON_WIN_ALPHA_MULT_SRC_SEL_MASK GENMASK(1, 0)
#define ZUMAPRO_DECON_WIN_ALPHA_MULT_SRC_AF	0x2
#define ZUMAPRO_DECON_WIN_FUNC_CON_1(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0008)
#define ZUMAPRO_DECON_WIN_FG_ALPHA_D_SEL(_v)	(((_v) & 0xf) << 24)
#define ZUMAPRO_DECON_WIN_BG_ALPHA_D_SEL(_v)	(((_v) & 0xf) << 16)
#define ZUMAPRO_DECON_WIN_FG_ALPHA_A_SEL(_v)	(((_v) & 0xf) << 8)
#define ZUMAPRO_DECON_WIN_BG_ALPHA_A_SEL(_v)	(((_v) & 0xf) << 0)
#define ZUMAPRO_DECON_WIN_BND_COEF_ZERO		0x0
#define ZUMAPRO_DECON_WIN_BND_COEF_ONE		0x1
#define ZUMAPRO_DECON_WIN_START_POSITION(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x000c)
#define ZUMAPRO_DECON_WIN_END_POSITION(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0010)
#define ZUMAPRO_DECON_WIN_COLORMAP_0(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0014)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_A(_v)	((_v) << 16)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_A_MASK	GENMASK(23, 16)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_R(_v)	((_v) << 0)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_R_MASK	GENMASK(9, 0)
#define ZUMAPRO_DECON_WIN_COLORMAP_1(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0018)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_G(_v)	((_v) << 16)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_G_MASK	GENMASK(25, 16)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_B(_v)	((_v) << 0)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_B_MASK	GENMASK(9, 0)
#define ZUMAPRO_DECON_WIN_START_TIME_CON(_id)	\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x001c)
#define ZUMAPRO_DECON_WIN_POS_Y(_v)		(((_v) & 0x3fff) << 16)
#define ZUMAPRO_DECON_WIN_POS_X(_v)		(((_v) & 0x3fff) << 0)

#define ZUMAPRO_DECON_CON_WIN(_id)		\
		(ZUMAPRO_DECON_WIN_OFFSET(_id) + 0x0000)
#define ZUMAPRO_DECON_WIN_CHMAP(_ch)		(((_ch) & 0xf) << 4)
#define ZUMAPRO_DECON_WIN_CHMAP_MASK		GENMASK(7, 4)
#define ZUMAPRO_DECON_WIN_MAPCOLOR_EN		BIT(1)
#define ZUMAPRO_DECON_WIN_EN			BIT(0)

/* DECON path values from downstream cal_common/decon_cal.h. */
#define ZUMAPRO_DECON_OUT_DSI0			BIT(0)
#define ZUMAPRO_DECON_OUT_DSI1			BIT(1)
#define ZUMAPRO_DECON_OUT_DP0			BIT(4)
#define ZUMAPRO_DECON_OUT_WB			BIT(8)

#define ZUMAPRO_DPATH_NOCOMP_OF0_DSIMIF0	0x001
#define ZUMAPRO_DPATH_DSC0_OF0_DSIMIF0		0x011
#define ZUMAPRO_DPATH_DSCC_DSC01_OF01_DSIMIF0	0x0b1
#define ZUMAPRO_DPATH_DSCC_DSC01_OF01_DSIMIF01	0x0b3
#define ZUMAPRO_DPATH_DSCC_DSCENC01_OUTFIFO01_DSIMIF0 \
	ZUMAPRO_DPATH_DSCC_DSC01_OF01_DSIMIF0

enum zumapro_decon_fifo {
	ZUMAPRO_DECON0_OFIFO0 = 0x0,
	ZUMAPRO_DECON0_OFIFO1 = 0x1,
	ZUMAPRO_DECON1_OFIFO0 = 0x2,
	ZUMAPRO_DECON_OFIFO_RSVD = 0x3,
	ZUMAPRO_DECON2_OFIFO0 = 0x4,
	ZUMAPRO_DECON_OFIFO_NONE = 0xf,
};

/* DECON sub bank: DSC and DSIMIF. */
#define ZUMAPRO_DSC_OFFSET(_id)			(0x1000 * (_id))
#define ZUMAPRO_DSIMIF_OFFSET(_id)		(0x8000 + 0x1000 * (_id))

#define ZUMAPRO_DSC_CONTROL0(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0000)
#define ZUMAPRO_DSC_CONTROL1(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0004)
#define ZUMAPRO_DSC_CONTROL3(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x000c)
#define ZUMAPRO_DSC_SW_RESET			BIT(28)
#define ZUMAPRO_DSC_COMP_SEL(_v)		((_v) << 24)
#define ZUMAPRO_DSC_COMP_SEL_MASK		BIT(24)
#define ZUMAPRO_DSC_SLICE_MODE_CH(_v)		((_v) << 1)
#define ZUMAPRO_DSC_SLICE_MODE_CH_MASK		BIT(1)
#define ZUMAPRO_DSC_DUAL_SLICE_EN(_v)		((_v) << 0)
#define ZUMAPRO_DSC_DUAL_SLICE_EN_MASK		BIT(0)
#define ZUMAPRO_DSC_REMAINDER(_v)		((_v) << 12)
#define ZUMAPRO_DSC_REMAINDER_MASK		GENMASK(13, 12)
#define ZUMAPRO_DSC_GRPCNTLINE(_v)		((_v) << 0)
#define ZUMAPRO_DSC_GRPCNTLINE_MASK		GENMASK(10, 0)

#define ZUMAPRO_DSC_PPS00_03(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0040)
#define ZUMAPRO_DSC_PPS04_07(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0044)
#define ZUMAPRO_DSC_PPS08_11(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0048)
#define ZUMAPRO_DSC_PPS12_15(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x004c)
#define ZUMAPRO_DSC_PPS16_19(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0050)
#define ZUMAPRO_DSC_PPS20_23(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0054)
#define ZUMAPRO_DSC_PPS24_27(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0058)
#define ZUMAPRO_DSC_PPS28_31(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x005c)
#define ZUMAPRO_DSC_PPS32_35(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0060)
#define ZUMAPRO_DSC_PPS36_39(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0064)
#define ZUMAPRO_DSC_PPS40_43(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0068)
#define ZUMAPRO_DSC_PPS44_47(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x006c)
#define ZUMAPRO_DSC_PPS48_51(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0070)
#define ZUMAPRO_DSC_PPS52_55(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0074)
#define ZUMAPRO_DSC_PPS56_59(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0078)
#define ZUMAPRO_DSC_PPS60_63(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x007c)
#define ZUMAPRO_DSC_PPS64_67(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0080)
#define ZUMAPRO_DSC_PPS68_71(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0084)
#define ZUMAPRO_DSC_PPS72_75(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0088)
#define ZUMAPRO_DSC_PPS76_79(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x008c)
#define ZUMAPRO_DSC_PPS80_83(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0090)
#define ZUMAPRO_DSC_PPS84_87(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0094)
#define ZUMAPRO_DSC_PPS92_95(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x0098)
#define ZUMAPRO_DSC_PPS96_99(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x009c)
#define ZUMAPRO_DSC_PPS100_103(_id)		(ZUMAPRO_DSC_OFFSET(_id) + 0x00a4)

#define ZUMAPRO_DSIMIF_SEL(_id)			(ZUMAPRO_DSIMIF_OFFSET(_id) + 0x0000)
#define ZUMAPRO_DSIMIF_SEL_DSIM(_v)		((_v) << 0)
#define ZUMAPRO_DSIMIF_SEL_DSIM_MASK		GENMASK(2, 0)
#define ZUMAPRO_DSIMIF_TE_TIMEOUT_CON(_id)	\
		(ZUMAPRO_DSIMIF_OFFSET(_id) + 0x0004)
#define ZUMAPRO_DSIMIF_START_TIME_CON(_id)	\
		(ZUMAPRO_DSIMIF_OFFSET(_id) + 0x0008)
#define ZUMAPRO_DSIMIF_LATE_START_ALARM_TH(_id)	\
		(ZUMAPRO_DSIMIF_OFFSET(_id) + 0x000c)

/* DQE register bank. */
#define ZUMAPRO_DQE_TOP_IMG_SIZE		0x0004
#define ZUMAPRO_DQE_TOP_FRM_SIZE		0x0008
#define ZUMAPRO_DQE_TOP_FRM_PXL_NUM		0x000c
#define ZUMAPRO_DQE_ATC_CONTROL			0x0400
#define ZUMAPRO_DQE_ATC_PARTIAL_IBSI_P1		0x0434
#define ZUMAPRO_DQE_ATC_PARTIAL_IBSI_P2		0x043c
#define ZUMAPRO_DQE_ATC_CDF_DIV			0x0448
#define ZUMAPRO_DQE_DISP_DITHER			0x2800
#define ZUMAPRO_DQE_DITHER_OFFSET_V4		0x0400
#define ZUMAPRO_DQE_DISP_DITHER_V4		\
		(ZUMAPRO_DQE_DISP_DITHER + ZUMAPRO_DQE_DITHER_OFFSET_V4)
#define ZUMAPRO_DQE_IMG_VSIZE(_v)		(((_v) & 0x3fff) << 16)
#define ZUMAPRO_DQE_IMG_HSIZE(_v)		(((_v) & 0x3fff) << 0)
#define ZUMAPRO_DQE_FULL_PXL_NUM(_v)		(((_v) & 0x0fffffff) << 0)
#define ZUMAPRO_DQE_ATC_IBSI_Y(_v)		(((_v) & 0xffff) << 16)
#define ZUMAPRO_DQE_ATC_IBSI_X(_v)		(((_v) & 0xffff) << 0)
#define ZUMAPRO_DQE_ATC_CDF_SHIFT(_v)		(((_v) & 0xf) << 16)
#define ZUMAPRO_DQE_ATC_CDF_DIV_VAL(_v)		(((_v) & 0x3fff) << 0)

/* DPP RDMA register bank. */
#define ZUMAPRO_DPP_DMA_SHD_OFFSET		0x0400
#define ZUMAPRO_RDMA_ENABLE			0x0000
#define ZUMAPRO_RDMA_ENABLE_SRESET		BIT(8)
#define ZUMAPRO_RDMA_ENABLE_SFR_UPDATE_FORCE	BIT(4)
#define ZUMAPRO_RDMA_ENABLE_OP_STATUS		BIT(2)
#define ZUMAPRO_RDMA_IRQ			0x0004
#define ZUMAPRO_RDMA_IRQ_CONFIG_ERR		BIT(21)
#define ZUMAPRO_RDMA_IRQ_INST_OFF_DONE		BIT(20)
#define ZUMAPRO_RDMA_IRQ_READ_SLAVE_ERR		BIT(19)
#define ZUMAPRO_RDMA_IRQ_DEADLOCK		BIT(17)
#define ZUMAPRO_RDMA_IRQ_FRAME_DONE		BIT(16)
#define ZUMAPRO_RDMA_IRQ_ALL_CLEAR		(0x0dfb << 16)
#define ZUMAPRO_RDMA_IRQ_ALL_MASK		(0x0dfb << 1)
#define ZUMAPRO_RDMA_IRQ_ENABLE			BIT(0)

#define ZUMAPRO_RDMA_ENABLE_ASSIGNED_MO(_v)	((_v) << 24)
#define ZUMAPRO_RDMA_ENABLE_ASSIGNED_MO_MASK	GENMASK(31, 24)

#define ZUMAPRO_RDMA_IN_CTRL_0			0x0008
#define ZUMAPRO_RDMA_ALPHA(_v)			((_v) << 24)
#define ZUMAPRO_RDMA_ALPHA_MASK			GENMASK(31, 24)
#define ZUMAPRO_RDMA_IC_MAX(_v)			((_v) << 16)
#define ZUMAPRO_RDMA_IC_MAX_MASK		GENMASK(23, 16)
#define ZUMAPRO_RDMA_IMG_FORMAT(_v)		((_v) << 8)
#define ZUMAPRO_RDMA_IMG_FORMAT_MASK		GENMASK(13, 8)
#define ZUMAPRO_RDMA_ROT(_v)			((_v) << 4)
#define ZUMAPRO_RDMA_ROT_MASK			GENMASK(6, 4)
#define ZUMAPRO_RDMA_AFBC_EN			BIT(3)
#define ZUMAPRO_RDMA_SBWC_EN			BIT(2)
#define ZUMAPRO_RDMA_SAJC_EN			BIT(1)
#define ZUMAPRO_RDMA_BLOCK_EN			BIT(0)

#define ZUMAPRO_RDMA_SRC_WIDTH			0x0010
#define ZUMAPRO_RDMA_SRC_HEIGHT			0x0014
#define ZUMAPRO_RDMA_SRC_OFFSET			0x0018
#define ZUMAPRO_RDMA_SRC_OFFSET_Y(_v)		((_v) << 16)
#define ZUMAPRO_RDMA_SRC_OFFSET_Y_MASK		GENMASK(31, 16)
#define ZUMAPRO_RDMA_SRC_OFFSET_X(_v)		((_v) << 0)
#define ZUMAPRO_RDMA_SRC_OFFSET_X_MASK		GENMASK(15, 0)
#define ZUMAPRO_RDMA_IMG_SIZE			0x001c
#define ZUMAPRO_RDMA_BLOCK_OFFSET		0x0020
#define ZUMAPRO_RDMA_BLOCK_SIZE			0x0024
#define ZUMAPRO_RDMA_BASEADDR_P0		0x0040
#define ZUMAPRO_RDMA_BASEADDR_P1		0x0044
#define ZUMAPRO_RDMA_SRC_STRIDE_0		0x0050
#define ZUMAPRO_RDMA_SIZE_HEIGHT(_v)		((_v) << 16)
#define ZUMAPRO_RDMA_SIZE_HEIGHT_MASK		GENMASK(31, 16)
#define ZUMAPRO_RDMA_SIZE_WIDTH(_v)		((_v) << 0)
#define ZUMAPRO_RDMA_SIZE_WIDTH_MASK		GENMASK(15, 0)
#define ZUMAPRO_RDMA_STRIDE_0(_v)		((_v) << 0)
#define ZUMAPRO_RDMA_STRIDE_0_MASK		GENMASK(23, 0)

#define ZUMAPRO_RDMA_RECOVERY_CTRL		0x0080
#define ZUMAPRO_RDMA_RECOVERY_NUM(_v)		((_v) << 1)
#define ZUMAPRO_RDMA_RECOVERY_NUM_MASK		GENMASK(31, 1)
#define ZUMAPRO_RDMA_RECOVERY_EN		BIT(0)

#define ZUMAPRO_RDMA_DEADLOCK_CTRL		0x0100
#define ZUMAPRO_RDMA_DEADLOCK_NUM(_v)		((_v) << 1)
#define ZUMAPRO_RDMA_DEADLOCK_NUM_MASK		GENMASK(31, 1)
#define ZUMAPRO_RDMA_DEADLOCK_NUM_EN		BIT(0)

#define ZUMAPRO_RDMA_QOS_LUT_LOW		0x0130
#define ZUMAPRO_RDMA_QOS_LUT_HIGH		0x0134

#define ZUMAPRO_RDMA_DYNAMIC_GATING_EN		0x0140
#define ZUMAPRO_RDMA_SRAM_CG_EN			BIT(31)
#define ZUMAPRO_RDMA_DG_EN_ALL			GENMASK(30, 0)

enum zumapro_dpu_dma_format {
	ZUMAPRO_DMA_FORMAT_BGRA8888 = 0,
	ZUMAPRO_DMA_FORMAT_RGBA8888 = 1,
	ZUMAPRO_DMA_FORMAT_ABGR8888 = 2,
	ZUMAPRO_DMA_FORMAT_ARGB8888 = 3,
	ZUMAPRO_DMA_FORMAT_BGRX8888 = 4,
	ZUMAPRO_DMA_FORMAT_RGBX8888 = 5,
	ZUMAPRO_DMA_FORMAT_XBGR8888 = 6,
	ZUMAPRO_DMA_FORMAT_XRGB8888 = 7,
	ZUMAPRO_DMA_FORMAT_BGR565 = 8,
	ZUMAPRO_DMA_FORMAT_RGB565 = 9,
	ZUMAPRO_DMA_FORMAT_BGRA1010102 = 16,
	ZUMAPRO_DMA_FORMAT_RGBA1010102 = 17,
	ZUMAPRO_DMA_FORMAT_ABGR2101010 = 18,
	ZUMAPRO_DMA_FORMAT_ARGB2101010 = 19,
	ZUMAPRO_DMA_FORMAT_NV21 = 24,
	ZUMAPRO_DMA_FORMAT_NV12 = 25,
	ZUMAPRO_DMA_FORMAT_YVU420_8P2 = 26,
	ZUMAPRO_DMA_FORMAT_YUV420_8P2 = 27,
	ZUMAPRO_DMA_FORMAT_YVU420_P010 = 28,
	ZUMAPRO_DMA_FORMAT_YUV420_P010 = 29,
	ZUMAPRO_DMA_FORMAT_ARGB_FP16 = 32,
	ZUMAPRO_DMA_FORMAT_ABGR_FP16 = 33,
	ZUMAPRO_DMA_FORMAT_RGBA_FP16 = 34,
	ZUMAPRO_DMA_FORMAT_BGRA_FP16 = 35,
	ZUMAPRO_DMA_FORMAT_NV61 = 56,
	ZUMAPRO_DMA_FORMAT_NV16 = 57,
	ZUMAPRO_DMA_FORMAT_YVU422_8P2 = 58,
	ZUMAPRO_DMA_FORMAT_YUV422_8P2 = 59,
	ZUMAPRO_DMA_FORMAT_YVU422_P210 = 60,
	ZUMAPRO_DMA_FORMAT_YUV422_P210 = 61,
};

/* DPP common register bank. */
#define ZUMAPRO_DPP_COM_SHD_OFFSET		0x0100
#define ZUMAPRO_DPP_COM_SWRST_CON		0x0004
#define ZUMAPRO_DPP_COM_IRQ_CON			0x0010
#define ZUMAPRO_DPP_COM_IRQ_MASK		0x0014
#define ZUMAPRO_DPP_COM_IRQ_STATUS		0x0018
#define ZUMAPRO_DPP_COM_CFG_ERROR_STATUS	0x001c
#define ZUMAPRO_DPP_COM_IO_CON			0x0038
#define ZUMAPRO_DPP_ALPHA_SEL_PER_PIXEL		BIT(7)
#define ZUMAPRO_DPP_BPC_MODE_10BIT		BIT(6)
#define ZUMAPRO_DPP_COM_IMG_SIZE		0x003c
#define ZUMAPRO_DPP_SRESET			BIT(0)
#define ZUMAPRO_DPP_IRQ_EN			BIT(0)
#define ZUMAPRO_DPP_CFG_ERROR_MASK		BIT(1)
#define ZUMAPRO_DPP_FRM_DONE_MASK		BIT(0)
#define ZUMAPRO_DPP_IMG_FORMAT(_v)		((_v) << 0)
#define ZUMAPRO_DPP_IMG_FORMAT_MASK		GENMASK(2, 0)
#define ZUMAPRO_DPP_IMG_SIZE_HEIGHT(_v)		((_v) << 16)
#define ZUMAPRO_DPP_IMG_SIZE_HEIGHT_MASK	GENMASK(29, 16)
#define ZUMAPRO_DPP_IMG_SIZE_WIDTH(_v)		((_v) << 0)
#define ZUMAPRO_DPP_IMG_SIZE_WIDTH_MASK		GENMASK(13, 0)

#define ZUMAPRO_DPP_COM_SCL_CTRL		0x0080
#define ZUMAPRO_DPP_SCL_ENABLE			BIT(0)
#define ZUMAPRO_DPP_COM_SCL_SCALED_IMG_SIZE	0x0084
#define ZUMAPRO_DPP_COM_SCL_HPOSITION		0x0090
#define ZUMAPRO_DPP_COM_SCL_VPOSITION		0x0094

/* DPP SRAM controller register bank. */
#define ZUMAPRO_SRAMC_COM_MODE			0x0010
#define ZUMAPRO_SRAMC_SCL_ALPHA_EN		BIT(13)
#define ZUMAPRO_SRAMC_SCL_EN			BIT(12)
#define ZUMAPRO_SRAMC_COMP_YUV_MODE		BIT(10)
#define ZUMAPRO_SRAMC_COMP_EN			BIT(8)
#define ZUMAPRO_SRAMC_ROT_EN			BIT(4)
#define ZUMAPRO_SRAMC_YUV_MODE			BIT(2)
#define ZUMAPRO_SRAMC_FORMAT(_v)		((_v) << 0)
#define ZUMAPRO_SRAMC_FORMAT_MASK		GENMASK(1, 0)
#define ZUMAPRO_SRAMC_FMT_RGB32BIT		0
#define ZUMAPRO_SRAMC_FMT_RGB16BIT		1
#define ZUMAPRO_SRAMC_FMT_YUV8BIT		2
#define ZUMAPRO_SRAMC_FMT_YUV10BIT		3
#define ZUMAPRO_SRAMC_COM_DST_POSITION		0x0014
#define ZUMAPRO_SRAMC_DST_BOTTOM(_v)		(((_v) & 0x3fff) << 16)
#define ZUMAPRO_SRAMC_DST_TOP(_v)		(((_v) & 0x3fff) << 0)

/* DPP HDR_COMM (LSI_COMM) register bank. */
#define ZUMAPRO_LSI_COMM_IO_CON			0x000c
#define ZUMAPRO_COMM_BPC_MODE_10BIT		BIT(6)
#define ZUMAPRO_COMM_IMG_FORMAT(_v)		((_v) << 0)
#define ZUMAPRO_COMM_IMG_FORMAT_MASK		GENMASK(2, 0)
#define ZUMAPRO_LSI_COMM_SIZE			0x0020
#define ZUMAPRO_COMM_SIZE_VSIZE(_v)		(((_v) & 0x1fff) << 16)
#define ZUMAPRO_COMM_SIZE_HSIZE(_v)		(((_v) & 0x1fff) << 0)

enum zumapro_dpu_dpp_format {
	ZUMAPRO_DPP_FORMAT_ARGB8888 = 0,
	ZUMAPRO_DPP_FORMAT_ARGB8101010 = 1,
	ZUMAPRO_DPP_FORMAT_YUV420_8P = 2,
	ZUMAPRO_DPP_FORMAT_YUV420_P010 = 3,
	ZUMAPRO_DPP_FORMAT_YUV420_8P2 = 4,
	ZUMAPRO_DPP_FORMAT_YUV422_8P = 5,
	ZUMAPRO_DPP_FORMAT_YUV422_P210 = 6,
	ZUMAPRO_DPP_FORMAT_YUV422_8P2 = 7,
};

#endif /* __REGS_ZUMAPRO_DPU_H__ */
