# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_GOOGLE_AOC)	+= aoc.o
obj-$(CONFIG_GOOGLE_AOC_CHANNEL)	+= aoc-channel.o
obj-$(CONFIG_GOOGLE_AOC_USF)	+= aoc-usf.o
aoc-usf-y			:= usf-core.o usf-proto.o
