// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) Google LLC
 *
 * "Boot handoff" panel driver for the Pixel 9 Pro (caiman) MIPI-DSI
 * display.
 *
 * The bootloader fully initialises this panel - DCPHY PLL, DSIM link and the
 * panel's own power-on command sequence - and leaves it streaming (that is
 * what the simple-framebuffer splash is drawn into). This driver therefore
 * does NOT re-initialise the panel: prepare()/enable() are no-ops so the
 * running link is preserved, and the exynos9 DECON simply takes over scanning
 * its own framebuffer into the already-configured DSIM -> panel path.
 *
 * All this driver contributes is the DRM plumbing the DSI host needs: the DSI
 * device parameters (lane count, pixel format, command/video mode) and the
 * fixed native mode. Only the active resolution matters to the DECON; the
 * blanking is generated by the DSIM, which keeps the bootloader's values.
 */

#include <linux/backlight.h>
#include <linux/delay.h>
#include <linux/gpio/consumer.h>
#include <linux/module.h>
#include <linux/of.h>

#include <video/mipi_display.h>

#include <drm/display/drm_dsc.h>
#include <drm/display/drm_dsc_helper.h>
#include <drm/drm_connector.h>
#include <drm/drm_crtc.h>
#include <drm/drm_mipi_dsi.h>
#include <drm/drm_modes.h>
#include <drm/drm_panel.h>

/*
 * Leave the DDIC exactly as the bootloader configured it: no reset, no DCS at
 * all. The bootloader drives this panel lit and compressed, so this isolates
 * the DECON's stream from this driver's own init sequence.
 */
static bool caiman_handoff;
module_param_named(handoff, caiman_handoff, bool, 0644);
MODULE_PARM_DESC(handoff, "leave the panel in the bootloader's state");

struct caiman_panel {
	struct drm_panel panel;
	struct mipi_dsi_device *dsi;
	/*
	 * Cached in get_modes() so enable() can read the active mode's refresh
	 * rate (connector->state->crtc->state), the idiomatic way a drm_panel
	 * learns its mode - see panel-novatek-nt35950.c. drm_panel itself has no
	 * mode_set callback.
	 */
	struct drm_connector *connector;
	struct gpio_desc *reset_gpio;
};

/*
 * caiman (google,gs-cm4) DSC configurations, copied verbatim from the vendor
 * panel driver's wqhd_pps_config / fhd_pps_config. This is the compression the
 * DECON emits; the panel's own DSC decoder must be programmed to match, which
 * is what enable() sends (the vendor cm4_enable(): DCS 0x9D 0x01 + this PPS).
 *
 * Both resolutions run two slices, 8 bpc, 8.0 bpp; only the geometry-derived
 * fields (slice/picture width, delays, the scale/slice bpg offsets) differ.
 */
static const struct drm_dsc_config caiman_wqhd_dsc = {
	.line_buf_depth = 9,
	.bits_per_component = 8,
	.convert_rgb = true,
	.slice_width = 640,
	.slice_height = 42,
	.slice_count = 2,
	.simple_422 = false,
	.pic_width = 1280,
	.pic_height = 2856,
	.rc_tgt_offset_high = 3,
	.rc_tgt_offset_low = 3,
	.bits_per_pixel = 128,
	.rc_edge_factor = 6,
	.rc_quant_incr_limit1 = 11,
	.rc_quant_incr_limit0 = 11,
	.initial_xmit_delay = 512,
	.initial_dec_delay = 577,
	.block_pred_enable = true,
	.first_line_bpg_offset = 12,
	.initial_offset = 6144,
	.rc_buf_thresh = {
		14, 28, 42, 56, 70, 84, 98, 105,
		112, 119, 121, 123, 125, 126
	},
	.rc_range_params = {
		{ 0, 4, 2 }, { 0, 4, 0 }, { 1, 5, 0 }, { 1, 6, 62 },
		{ 3, 7, 60 }, { 3, 7, 58 }, { 3, 7, 56 }, { 3, 8, 56 },
		{ 3, 9, 56 }, { 3, 10, 54 }, { 5, 11, 54 }, { 5, 12, 52 },
		{ 5, 13, 52 }, { 7, 13, 52 }, { 13, 15, 52 }
	},
	.rc_model_size = 8192,
	.flatness_min_qp = 3,
	.flatness_max_qp = 12,
	.initial_scale_value = 32,
	.scale_decrement_interval = 8,
	.scale_increment_interval = 1130,
	.nfl_bpg_offset = 600,
	.slice_bpg_offset = 522,
	.final_offset = 4336,
	.vbr_enable = false,
	.slice_chunk_size = 640,
	.dsc_version_minor = 2,
	.dsc_version_major = 1,
};

static const struct drm_dsc_config caiman_fhd_dsc = {
	.line_buf_depth = 9,
	.bits_per_component = 8,
	.convert_rgb = true,
	.slice_width = 480,
	.slice_height = 42,
	.slice_count = 2,
	.simple_422 = false,
	.pic_width = 960,
	.pic_height = 2142,
	.rc_tgt_offset_high = 3,
	.rc_tgt_offset_low = 3,
	.bits_per_pixel = 128,
	.rc_edge_factor = 6,
	.rc_quant_incr_limit1 = 11,
	.rc_quant_incr_limit0 = 11,
	.initial_xmit_delay = 512,
	.initial_dec_delay = 496,
	.block_pred_enable = true,
	.first_line_bpg_offset = 12,
	.initial_offset = 6144,
	.rc_buf_thresh = {
		14, 28, 42, 56, 70, 84, 98, 105,
		112, 119, 121, 123, 125, 126
	},
	.rc_range_params = {
		{ 0, 4, 2 }, { 0, 4, 0 }, { 1, 5, 0 }, { 1, 6, 62 },
		{ 3, 7, 60 }, { 3, 7, 58 }, { 3, 7, 56 }, { 3, 8, 56 },
		{ 3, 9, 56 }, { 3, 10, 54 }, { 5, 11, 54 }, { 5, 12, 52 },
		{ 5, 13, 52 }, { 7, 13, 52 }, { 13, 15, 52 }
	},
	.rc_model_size = 8192,
	.flatness_min_qp = 3,
	.flatness_max_qp = 12,
	.initial_scale_value = 32,
	.scale_decrement_interval = 6,
	.scale_increment_interval = 977,
	.nfl_bpg_offset = 600,
	.slice_bpg_offset = 698,
	.final_offset = 4336,
	.vbr_enable = false,
	.slice_chunk_size = 480,
	.dsc_version_minor = 2,
	.dsc_version_major = 1,
};

static inline struct caiman_panel *to_caiman_panel(struct drm_panel *panel)
{
	return container_of(panel, struct caiman_panel, panel);
}

/*
 * A caiman display mode: a DRM timing plus the per-resolution DDIC programming
 * (its matching DSC config and the DCS image-size / bit-depth selectors) that
 * enable() must send. The refresh rate is carried by the timing itself.
 *
 * Timings are taken verbatim from the vendor panel driver, e.g. WQHD 60 Hz:
 *   DRM_MODE_TIMING(60, 1280, 80, 24, 46, 2856, 12, 4, 28)
 * i.e. hfp=80 hsa=24 hbp=46, vfp=12 vsa=4 vbp=28. Only hdisplay/vdisplay reach
 * the DECON; the DSIM retains the bootloader blanking. Both resolutions run the
 * same dual-DSC 8.0bpp link at 60/120 Hz.
 */
struct caiman_mode {
	struct drm_display_mode mode;
	const struct drm_dsc_config *dsc;
	u8 image_conf;		/* DCS 0xC3: image-size select */
	u8 depth_conf;		/* DCS 0xF2: bit-depth select */
};

#define CAIMAN_MODE(w, hfp, hsa, hbp, h, vfp, vsa, vbp, hz, flags)	\
	.mode = {							\
		.clock = ((w) + (hfp) + (hsa) + (hbp)) *		\
			 ((h) + (vfp) + (vsa) + (vbp)) * (hz) / 1000,	\
		.hdisplay = (w),					\
		.hsync_start = (w) + (hfp),				\
		.hsync_end = (w) + (hfp) + (hsa),			\
		.htotal = (w) + (hfp) + (hsa) + (hbp),			\
		.vdisplay = (h),					\
		.vsync_start = (h) + (vfp),				\
		.vsync_end = (h) + (vfp) + (vsa),			\
		.vtotal = (h) + (vfp) + (vsa) + (vbp),			\
		.width_mm = 66,						\
		.height_mm = 147,					\
		.type = DRM_MODE_TYPE_DRIVER | (flags),			\
	}

/*
 * WQHD (1280x2856) and FHD (960x2142), each selectable at 60/120 Hz. WQHD
 * 120 Hz is the preferred/default; the others are reachable via a modeset. The
 * DDIC switches resolution through the image-size (0xC3) and bit-depth (0xF2)
 * selectors and a matching DSC PPS, all carried per-mode here.
 */
static const struct caiman_mode caiman_modes[] = {
	{
		CAIMAN_MODE(1280, 80, 24, 46, 2856, 12, 4, 28,
			    120, DRM_MODE_TYPE_PREFERRED),
		.dsc = &caiman_wqhd_dsc, .image_conf = 0x0C, .depth_conf = 0x01,
	}, {
		CAIMAN_MODE(1280, 80, 24, 46, 2856, 12, 4, 28, 60, 0),
		.dsc = &caiman_wqhd_dsc, .image_conf = 0x0C, .depth_conf = 0x01,
	}, {
		CAIMAN_MODE(960, 80, 24, 46, 2142, 12, 4, 32, 120, 0),
		.dsc = &caiman_fhd_dsc, .image_conf = 0x0D, .depth_conf = 0x81,
	}, {
		CAIMAN_MODE(960, 80, 24, 46, 2142, 12, 4, 32, 60, 0),
		.dsc = &caiman_fhd_dsc, .image_conf = 0x0D, .depth_conf = 0x81,
	},
};

/* Panel is already powered and streaming from the bootloader: keep it as-is. */
static int caiman_panel_noop(struct drm_panel *panel)
{
	return 0;
}

/* vendor gs_panel_reset_helper timing: H 5ms, L 5ms, H 10ms */
static void caiman_reset(struct caiman_panel *ctx)
{
	gpiod_set_value_cansleep(ctx->reset_gpio, 1);
	usleep_range(5000, 5100);
	gpiod_set_value_cansleep(ctx->reset_gpio, 0);
	usleep_range(5000, 5100);
	gpiod_set_value_cansleep(ctx->reset_gpio, 1);
	usleep_range(10000, 10100);
}

/* Hardware-reset the panel before every power-on (the driver owns the DDIC). */
static int caiman_panel_prepare(struct drm_panel *panel)
{
	struct caiman_panel *ctx = to_caiman_panel(panel);

	if (ctx->reset_gpio && !caiman_handoff)
		caiman_reset(ctx);
	return 0;
}

/* Sleep the panel down; the next enable fully re-initialises it. */
static int caiman_panel_disable(struct drm_panel *panel)
{
	struct caiman_panel *ctx = to_caiman_panel(panel);

	if (caiman_handoff)
		return 0;

	mipi_dsi_dcs_set_display_off(ctx->dsi);
	mipi_dsi_dcs_enter_sleep_mode(ctx->dsi);
	return 0;
}

/*
 * The bootloader powered the panel and ran its full init, but the DECON now
 * drives a freshly-programmed dual-DSC command stream. (Re)program the panel's
 * DSC decoder to match, mirroring the vendor cm4_enable() DSC path, and
 * (re)assert TE + display-on so the panel accepts the DECON-driven GRAM writes.
 */
/* Send a DCS command with inline bytes (cmd + params) to the panel. */
#define caiman_dcs(dsi, seq...)                                                  \
	mipi_dsi_dcs_write_buffer((dsi), (const u8[]){ seq },                  \
				  sizeof((const u8[]){ seq }))

static const struct caiman_mode *caiman_cur_mode(struct caiman_panel *ctx);

static int caiman_panel_enable(struct drm_panel *panel)
{
	struct caiman_panel *ctx = to_caiman_panel(panel);
	struct mipi_dsi_device *dsi = ctx->dsi;
	const struct caiman_mode *cm = caiman_cur_mode(ctx);
	const struct drm_display_mode *mode = &cm->mode;
	struct drm_dsc_picture_parameter_set pps;
	static const u8 dsc_en[] = { 0x9D, 0x01 };
	u16 xe = mode->hdisplay - 1;
	u16 ye = mode->vdisplay - 1;
	int ret;

	if (caiman_handoff)
		return 0;

	/*
	 * Full power-on (vendor cm4_enable, needs_reset path): the panel was just
	 * hardware-reset in prepare(), so program its DSC decoder, sleep it out,
	 * run the init cmdset and put it into continuous HS operation (early-exit
	 * OFF, manual FI OFF) so it accepts the DECON-driven write_memory, then
	 * send Display On.
	 */

	/* DSC: enable + PPS (vendor: 0x9D 0x01 + gs_dcs_write_dsc_config()) */
	mipi_dsi_dcs_write_buffer(dsi, dsc_en, sizeof(dsc_en));
	drm_dsc_pps_payload_pack(&pps, cm->dsc);
	ret = mipi_dsi_picture_parameter_set(dsi, &pps);
	if (ret < 0)
		dev_err(&dsi->dev, "failed to send DSC PPS: %d\n", ret);

	/*
	 * Sleep-out + the vendor cm4_init cmdset (TE on, full-screen CASET/PASET,
	 * FFC for 1368 Mbps, OPEC, PMIC fast-discharge off). The panel was just
	 * hardware-reset in prepare(), so it starts from a known state.
	 */
	caiman_dcs(dsi, MIPI_DCS_EXIT_SLEEP_MODE);
	msleep(120);
	caiman_dcs(dsi, MIPI_DCS_SET_TEAR_ON);
	caiman_dcs(dsi, 0x2A, 0x00, 0x00, xe >> 8, xe & 0xFF);	/* CASET */
	caiman_dcs(dsi, 0x2B, 0x00, 0x00, ye >> 8, ye & 0xFF);	/* PASET */
	caiman_dcs(dsi, 0xF0, 0x5A, 0x5A);			/* unlock */
	caiman_dcs(dsi, 0xB0, 0x00, 0x36, 0xC5);			/* FFC 1368Mbps */
	caiman_dcs(dsi, 0xC5, 0x10, 0x10, 0x50, 0x05, 0x4D, 0x31, 0x40,
		 0x00, 0x40, 0x00, 0x40, 0x00, 0x4D, 0x31, 0x40, 0x00,
		 0x40, 0x00, 0x40, 0x00, 0x4D, 0x31, 0x40, 0x00, 0x40,
		 0x00, 0x40, 0x00, 0x4D, 0x31, 0x40, 0x00, 0x40, 0x00,
		 0x40, 0x00);
	caiman_dcs(dsi, 0xB0, 0x00, 0x1D, 0x63);			/* OPEC enable */
	caiman_dcs(dsi, 0x63, 0x02, 0x18);
	caiman_dcs(dsi, 0xB0, 0x00, 0x13, 0xB1);			/* PMIC FD off */
	caiman_dcs(dsi, 0xB1, 0x80);
	caiman_dcs(dsi, 0xF7, 0x0F);				/* freq update */
	caiman_dcs(dsi, 0xF0, 0xA5, 0xA5);			/* lock */

	/* Resolution / bit-depth config block (per-mode image + depth select) */
	caiman_dcs(dsi, 0xF0, 0x5A, 0x5A);				/* unlock */
	caiman_dcs(dsi, 0xC3, cm->image_conf);			/* image size */
	caiman_dcs(dsi, 0xB0, 0x00, 0x01, 0xF2);
	caiman_dcs(dsi, 0xF2, cm->depth_conf);			/* bit depth */
	caiman_dcs(dsi, 0xF0, 0xA5, 0xA5);				/* lock */

	/*
	 * Full vendor cm4_set_panel_feat() block for a fresh 60Hz HS enable
	 * (mrr-v1, no idle/HBM/VRR, IRC flat default). Sent as flat DCS writes
	 * to the running (bootloader-lit) panel.
	 */
	caiman_dcs(dsi, 0xF0, 0x5A, 0x5A);				/* unlock */
	/* TE (changeable), EVT1-and-later width */
	caiman_dcs(dsi, 0xB9, 0x04);
	caiman_dcs(dsi, 0xB0, 0x00, 0x04, 0xB9);
	caiman_dcs(dsi, 0xB9, 0x0B, 0x1E, 0x00, 0x1F);
	/* HBM / IRC (flat default) */
	caiman_dcs(dsi, 0xB0, 0x02, 0x00, 0x92);
	caiman_dcs(dsi, 0x92, 0x00, 0x00, 0xFF, 0xD0);
	/* SP / burn-in settings, PVT-and-later values */
	caiman_dcs(dsi, 0xB0, 0x02, 0xF3, 0x68);
	caiman_dcs(dsi, 0x68, 0x10, 0x18, 0x13, 0x18, 0x20, 0x18);
	/* operating mode: HS */
	caiman_dcs(dsi, 0xF2, 0x01);
	caiman_dcs(dsi, 0x60, 0x00);
	/* early-exit off */
	caiman_dcs(dsi, 0xB0, 0x00, 0x01, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x81);
	caiman_dcs(dsi, 0xB0, 0x00, 0x10, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x00);
	caiman_dcs(dsi, 0xB0, 0x00, 0x82, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x00, 0x00, 0x00, 0x00);
	/* manual FI off */
	caiman_dcs(dsi, 0xB0, 0x00, 0x10, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x00);
	caiman_dcs(dsi, 0xB0, 0x00, 0x82, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x00, 0x00);
	caiman_dcs(dsi, 0xB0, 0x00, 0x80, 0xBD);
	caiman_dcs(dsi, 0xBD, 0x16);
	/* TSP sync */
	caiman_dcs(dsi, 0xB0, 0x00, 0x3C, 0xB9);
	caiman_dcs(dsi, 0xB9, 0x19, 0x09);
	caiman_dcs(dsi, 0xB0, 0x00, 0x05, 0xF2);
	caiman_dcs(dsi, 0xF2, 0xD0);
	caiman_dcs(dsi, 0xB0, 0x00, 0x41, 0xB9);
	caiman_dcs(dsi, 0xB9, 0x02);
	/* DBI reference frequency (vendor cm4_set_panel_feat_dbi, 120Hz only) */
	if (drm_mode_vrefresh(mode) == 120) {
		caiman_dcs(dsi, 0xB0, 0x00, 0x67, 0x69);
		caiman_dcs(dsi, 0x69, 60);
	}
	/* frequency: manual HS - 0x60 selects the rate (0x00 = 120Hz, 0x01 = 60Hz) */
	caiman_dcs(dsi, 0xBD, 0x21);
	caiman_dcs(dsi, 0x60, drm_mode_vrefresh(mode) == 120 ? 0x00 : 0x01);
	caiman_dcs(dsi, 0xF7, 0x0F);					/* freq update */
	caiman_dcs(dsi, 0xF0, 0xA5, 0xA5);				/* lock */

	/* WRCTRLD: enable brightness control (vendor cm4_write_display_mode) */
	caiman_dcs(dsi, 0x53, 0x20);

	mipi_dsi_dcs_set_display_on(dsi);

	return 0;
}

static int caiman_panel_get_modes(struct drm_panel *panel,
				  struct drm_connector *connector)
{
	struct caiman_panel *ctx = to_caiman_panel(panel);
	unsigned int i;

	/* cache for cur_vrefresh() in enable() */
	ctx->connector = connector;

	for (i = 0; i < ARRAY_SIZE(caiman_modes); i++) {
		struct drm_display_mode *mode;

		mode = drm_mode_duplicate(connector->dev, &caiman_modes[i].mode);
		if (!mode)
			return i ? i : -ENOMEM;

		drm_mode_set_name(mode);
		drm_mode_probed_add(connector, mode);
	}

	connector->display_info.width_mm = caiman_modes[0].mode.width_mm;
	connector->display_info.height_mm = caiman_modes[0].mode.height_mm;

	return ARRAY_SIZE(caiman_modes);
}

/*
 * Find the descriptor for the active mode. drm_panel has no mode_set, so reach
 * the committed mode through the cached connector's atomic state (valid during
 * the enable phase of a modeset) and match it against the mode table. Defaults
 * to the preferred mode (index 0) if the state is not available.
 */
static const struct caiman_mode *caiman_cur_mode(struct caiman_panel *ctx)
{
	struct drm_connector *conn = ctx->connector;
	const struct drm_display_mode *cur;
	unsigned int i;

	if (!conn || !conn->state || !conn->state->crtc ||
	    !conn->state->crtc->state)
		return &caiman_modes[0];

	cur = &conn->state->crtc->state->adjusted_mode;
	for (i = 0; i < ARRAY_SIZE(caiman_modes); i++)
		if (drm_mode_match(cur, &caiman_modes[i].mode,
				   DRM_MODE_MATCH_TIMINGS))
			return &caiman_modes[i];

	return &caiman_modes[0];
}

static const struct drm_panel_funcs caiman_panel_funcs = {
	.prepare = caiman_panel_prepare,
	.unprepare = caiman_panel_noop,
	.enable = caiman_panel_enable,
	.disable = caiman_panel_disable,
	.get_modes = caiman_panel_get_modes,
};

/*
 * Brightness: the panel level is a 12-bit DBV programmed over DSI (DCS 0x51,
 * MSB first - exactly mipi_dsi_dcs_set_display_brightness_large()). The enable
 * sequence already arms the brightness path (WRCTRLD BCTRL, 0x53 0x20).
 * Registering a backlight_device exposes /sys/class/backlight control, and
 * drm_panel enables/disables it around the panel so the DCS write only happens
 * while the link is up. The normal range tops out around DBV 3271; higher
 * values are the panel's HBM band, which needs its own enable sequence to
 * engage fully (not wired up yet).
 */
#define CAIMAN_BRIGHTNESS_MAX	4095
#define CAIMAN_BRIGHTNESS_DEFAULT 1300

static int caiman_bl_update_status(struct backlight_device *bl)
{
	struct caiman_panel *ctx = bl_get_data(bl);
	u16 brightness = backlight_get_brightness(bl);

	if (caiman_handoff)
		return 0;

	return mipi_dsi_dcs_set_display_brightness_large(ctx->dsi, brightness);
}

static const struct backlight_ops caiman_bl_ops = {
	.update_status = caiman_bl_update_status,
};

static int caiman_panel_backlight_init(struct caiman_panel *ctx)
{
	struct device *dev = &ctx->dsi->dev;
	const struct backlight_properties props = {
		.type = BACKLIGHT_RAW,
		.brightness = CAIMAN_BRIGHTNESS_DEFAULT,
		.max_brightness = CAIMAN_BRIGHTNESS_MAX,
	};
	struct backlight_device *bl;

	bl = devm_backlight_device_register(dev, dev_name(dev), dev, ctx,
					    &caiman_bl_ops, &props);
	if (IS_ERR(bl))
		return PTR_ERR(bl);

	ctx->panel.backlight = bl;
	return 0;
}

static int caiman_panel_probe(struct mipi_dsi_device *dsi)
{
	struct device *dev = &dsi->dev;
	struct caiman_panel *ctx;
	int ret;

	ctx = devm_drm_panel_alloc(dev, struct caiman_panel, panel,
				   &caiman_panel_funcs,
				   DRM_MODE_CONNECTOR_DSI);
	if (IS_ERR(ctx))
		return PTR_ERR(ctx);

	ctx->dsi = dsi;
	mipi_dsi_set_drvdata(dsi, ctx);

	/*
	 * DDIC reset, pulsed on every prepare() to bring the panel up from a
	 * known state. Requested OUT_HIGH (the panel's run state) so the brief
	 * window before the first prepare does not disturb a bootloader-lit
	 * panel. Optional, but required in practice for a cold power-on.
	 */
	ctx->reset_gpio = devm_gpiod_get_optional(dev, "reset", GPIOD_OUT_HIGH);
	if (IS_ERR(ctx->reset_gpio))
		return dev_err_probe(dev, PTR_ERR(ctx->reset_gpio),
				     "failed to get reset gpio\n");

	dsi->lanes = 4;
	dsi->format = MIPI_DSI_FMT_RGB888;
	/*
	 * Per-lane HS bit rate of the bootloader-trained link. The DSIM host
	 * reads this (instead of hardcoding it) to size the command-mode TE
	 * transfer window and compute the PLL for a cold link bring-up.
	 */
	dsi->hs_rate = 1368000000;
	/* publish the DSC config so the DSIM/DECON can program compression */
	dsi->dsc = (struct drm_dsc_config *)&caiman_wqhd_dsc;
	/*
	 * The caiman panel runs in MIPI command mode (LTPO OLED); the DECON is
	 * hardware-triggered from the panel TE. If a given unit's bootloader
	 * left the link in video mode instead, add MIPI_DSI_MODE_VIDEO here.
	 */
	dsi->mode_flags = MIPI_DSI_CLOCK_NON_CONTINUOUS;

	ctx->panel.prepare_prev_first = true;

	ret = caiman_panel_backlight_init(ctx);
	if (ret)
		return dev_err_probe(dev, ret, "failed to register backlight\n");

	drm_panel_add(&ctx->panel);

	ret = mipi_dsi_attach(dsi);
	if (ret < 0) {
		drm_panel_remove(&ctx->panel);
		return dev_err_probe(dev, ret, "failed to attach to DSI host\n");
	}

	return 0;
}

static void caiman_panel_remove(struct mipi_dsi_device *dsi)
{
	struct caiman_panel *ctx = mipi_dsi_get_drvdata(dsi);

	mipi_dsi_detach(dsi);
	drm_panel_remove(&ctx->panel);
}

static const struct of_device_id caiman_panel_of_match[] = {
	{ .compatible = "google,caiman-panel" },
	{ }
};
MODULE_DEVICE_TABLE(of, caiman_panel_of_match);

static struct mipi_dsi_driver caiman_panel_driver = {
	.probe = caiman_panel_probe,
	.remove = caiman_panel_remove,
	.driver = {
		.name = "panel-google-caiman",
		.of_match_table = caiman_panel_of_match,
	},
};
module_mipi_dsi_driver(caiman_panel_driver);

MODULE_DESCRIPTION("Google caiman (Pixel 9 Pro XL) boot-handoff panel driver");
MODULE_LICENSE("GPL");
